### PR TITLE
Benchmark samples

### PR DESCRIPTION
**Pull request by TheAngryByrd**
## Known issues

Suave.LibUv on Mono still suffers from https://github.com/SuaveIO/suave/issues/360 and cannot get an accurate benchmark.

The Suave.LibUv on CoreCLR has trouble resolving packages and cannot be properly benchmarked

```
    Package Suave.LibUv 2.0.0-alpha4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Suave.LibUv 2.0.0-alpha4 supports: net40 (.NETFramework,Version=v4.0)
    Package FSharp.Core 3.1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package FSharp.Core 3.1.2.5 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net40 (.NETFramework,Version=v4.0)
      - portable-monoandroid10+monotouch10+net45+xamarinios10 (.NETPortable,Version=v0.0,Profile=net45+monoandroid10+monotouch10+xamarinios10)
      - portable-net45+sl5+win8 (.NETPortable,Version=v0.0,Profile=Profile47)
      - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

```
#### Also

What should I do about the giant  samples/SuaveOnMono/paket.lock files?

Anything else I should add?

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Whoops looks like I need to rebase.  I'll get on that.

**Comment by Krzysztof-Cieslak** [comment]
1. Let's put samples used for benchmark to `benchmark` folder, not to `samples`
2. I think that pinning framework version in `paket.dependencies` for mono versions should make both `fsproj` and `paket.lock` smaller

**Comment by TheAngryByrd** [comment]
Yep, that helped considerably.

**Comment by Krzysztof-Cieslak** [comment]
Thanks!

**Pull request merged**
